// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnI8m6divXZY0teCAbQ-Ai-A81EfaZs3Q',
    appId: '1:1007660997923:web:f18884551bd07fdb2bc096',
    messagingSenderId: '1007660997923',
    projectId: 'desamallapps',
    authDomain: 'desamallapps.firebaseapp.com',
    storageBucket: 'desamallapps.firebasestorage.app',
    measurementId: 'G-MLXDC07W2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCojgmxyrpSnRFAxpKtuGa_jHv4QM50d7g',
    appId: '1:1007660997923:android:dc63c32ac9ac9d962bc096',
    messagingSenderId: '1007660997923',
    projectId: 'desamallapps',
    storageBucket: 'desamallapps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZxOFqEh-UX76qILjh4NabYXHQSEivmSA',
    appId: '1:1007660997923:ios:b788d0a549fa7f2e2bc096',
    messagingSenderId: '1007660997923',
    projectId: 'desamallapps',
    storageBucket: 'desamallapps.firebasestorage.app',
    iosBundleId: 'com.example.desamallApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZxOFqEh-UX76qILjh4NabYXHQSEivmSA',
    appId: '1:1007660997923:ios:b788d0a549fa7f2e2bc096',
    messagingSenderId: '1007660997923',
    projectId: 'desamallapps',
    storageBucket: 'desamallapps.firebasestorage.app',
    iosBundleId: 'com.example.desamallApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnI8m6divXZY0teCAbQ-Ai-A81EfaZs3Q',
    appId: '1:1007660997923:web:caa8eea96854df0b2bc096',
    messagingSenderId: '1007660997923',
    projectId: 'desamallapps',
    authDomain: 'desamallapps.firebaseapp.com',
    storageBucket: 'desamallapps.firebasestorage.app',
    measurementId: 'G-EFSZBJ8JKL',
  );
}
